imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

anyt_file_search:
    dir: "%kernel.root_dir%/../web/tests_files"
    engine: "file_search.grep_engine"